import pytest
import numpy as np
import pandas as pd
import os
import tempfile
from toolkit.structure import Structure
from toolkit.io import Writefile, parse_cp2k_inp
from toolkit.io import _MASS_TO_ELEM
from conftest import data_path


LATTICE_CUBIC_10 = np.array([
    [10.0, 0.0, 0.0],
    [0.0, 10.0, 0.0],
    [0.0, 0.0, 10.0],
])


class TestWritefile:
    @pytest.fixture
    def wf(self):
        s = Structure(data_path('water.xyz'), lattice_params=[10,0,0,0,10,0,0,0,10])
        return Writefile(s.coord(), s.lattice())

    def test_write_vasp_cartesian(self, wf, tmp_path):
        out = tmp_path / 'test.vasp'
        wf.tovasp(str(out), direct=False)
        content = out.read_text()
        assert 'C' in content
        assert 'O' in content
        assert 'H' in content

    def test_write_vasp_direct(self, wf, tmp_path):
        out = tmp_path / 'test.vasp'
        wf.tovasp(str(out), direct=True)
        content = out.read_text()
        assert 'D' in content
        assert '0.500000' in content

    def test_write_vasp_roundtrip(self, wf, tmp_path):
        """Write VASP then read back, coords should match."""
        out = tmp_path / 'test.vasp'
        wf.tovasp(str(out), direct=False)
        s2 = Structure(str(out))
        np.testing.assert_array_almost_equal(s2.coord().to_numpy(),
                                             wf.coord.to_numpy())

    def test_write_xyz(self, wf, tmp_path):
        out = tmp_path / 'test.xyz'
        wf.toxyz(str(out))
        content = out.read_text()
        assert '3' in content  # atom count
        assert 'Generated by toolkit' in content

    def test_write_lammps_data(self, wf, tmp_path):
        out = tmp_path / 'test.data'
        wf.tolmp(str(out))
        content = out.read_text()
        assert 'atoms' in content
        assert 'Masses' in content
        assert 'Atoms' in content

    def test_write_lammps_roundtrip(self, wf, tmp_path):
        """Write LAMMPS data then read back, coords should match."""
        out = tmp_path / 'test.data'
        wf.tolmp(str(out))
        s2 = Structure(str(out))
        np.testing.assert_array_almost_equal(s2.coord().to_numpy(),
                                             wf.coord.to_numpy())

    def test_write_lammps_charge_style(self, wf, tmp_path):
        out = tmp_path / 'test.data'
        wf.tolmp(str(out), atom_style='charge')
        content = out.read_text()
        assert '# charge' in content.lower()

    def test_write_lammps_full_style(self, wf, tmp_path):
        out = tmp_path / 'test.data'
        wf.tolmp(str(out), atom_style='full')
        content = out.read_text()
        assert '# full' in content.lower()

    def test_write_lammps_triclinic(self, tmp_path):
        """Write triclinic lattice to LAMMPS data."""
        lattice = np.array([
            [13.0, 0.0, 0.0],
            [-6.5, 11.258, 0.0],
            [0.0, 0.0, 16.14],
        ])
        coord = pd.DataFrame({'x': [0.0], 'y': [0.0], 'z': [0.0]}, index=['H'])
        wf = Writefile(coord, lattice)
        out = tmp_path / 'test.data'
        wf.tolmp(str(out))
        content = out.read_text()
        assert 'xy xz yz' in content


class TestParseCP2KInp:
    def test_parse_6_params(self, tmp_path):
        inp = tmp_path / 'cp2k.inp'
        inp.write_text('ABC 10.0 10.0 10.0\nALPHA_BETA_GAMMA 90.0 90.0 90.0\n')
        result = parse_cp2k_inp(str(inp))
        assert result == [10.0, 10.0, 10.0, 90.0, 90.0, 90.0]

    def test_parse_9_params(self, tmp_path):
        inp = tmp_path / 'cp2k.inp'
        inp.write_text('A 10.0 0.0 0.0\nB 0.0 10.0 0.0\nC 0.0 0.0 10.0\n')
        result = parse_cp2k_inp(str(inp))
        assert result == [10.0, 0.0, 0.0, 0.0, 10.0, 0.0, 0.0, 0.0, 10.0]

    def test_file_not_found(self):
        result = parse_cp2k_inp('/nonexistent/cp2k.inp')
        assert result is None


class TestMassTable:
    def test_common_elements(self):
        assert 'H' in _MASS_TO_ELEM.values()
        assert 'O' in _MASS_TO_ELEM.values()
        assert 'C' in _MASS_TO_ELEM.values()
        assert 'Fe' in _MASS_TO_ELEM.values()
        assert 'Au' in _MASS_TO_ELEM.values()
