import numpy as np
import pandas as pd

from toolkit.structure import Structure, _MASS_TO_ELEM


def parse_cp2k_inp(filepath='cp2k.inp'):
    """Parse lattice parameters from a CP2K input file.

    Returns list of 6 (A,B,C,alpha,beta,gamma) or 9 (xx,xy,xz,...) values,
    or None if no cp2k.inp found.
    """
    try:
        with open(filepath, 'r') as f:
            lines = [x.rstrip().split() for x in f]
    except FileNotFoundError:
        return None

    lattice_params = []
    for i in lines:
        if not i:
            continue
        if i[0] == 'ABC':
            lattice_params.extend(float(x) for x in i[1:])
        elif i[0] == 'ALPHA_BETA_GAMMA':
            lattice_params.extend(float(x) for x in i[1:])
            return lattice_params
        elif i[0] in ('A', 'B', 'C'):
            lattice_params.extend(float(x) for x in i[1:])
            if i[0] == 'C':
                return lattice_params
    return lattice_params if lattice_params else None


class Writefile:
    """Write coord + lattice to structure files (POSCAR, XYZ)."""

    def __init__(self, coord, lattice, filename=None):
        self._coord = coord.sort_index()
        self._lattice = np.array(lattice, dtype=float)
        self._filename = filename

    @classmethod
    def from_file(cls, filename, lattice_params=None):
        """Create Writefile from a structure file."""
        s = Structure(filename, lattice_params)
        return cls(s.coord(), s.lattice(), filename)

    @property
    def coord(self):
        return self._coord

    @property
    def lattice(self):
        return self._lattice

    @staticmethod
    def _clean_elem_label(label):
        return str(label).replace("('", '').replace("',)", '')

    def tovasp(self, outfile='POSCAR', direct=True):
        """Write POSCAR file."""
        ele_type = self.coord.index.unique()
        ele_labels = [self._clean_elem_label(x) for x in ele_type]
        ele_counts = {x: len(self.coord.loc[[x]]) for x in ele_type}

        with open(outfile, 'w') as f:
            f.write('Generated by toolkit\n1.00000000000000\n')
            f.write('\n'.join(
                '\t'.join(f'{x:0.6f}' for x in row) for row in self.lattice
            ) + '\n')
            f.write(' '.join(ele_labels) + '\n')
            f.write(' '.join(str(ele_counts[x]) for x in ele_type) + '\n')

            if direct:
                direct_coord = np.dot(self.coord, np.linalg.inv(self.lattice))
                f.write('D\n')
                f.write('\n'.join(
                    '\t'.join(f'{x:0.6f}' for x in row) for row in direct_coord
                ))
            else:
                f.write('C\n')
                f.write('\n'.join(
                    '\t'.join(f'{x:0.6f}' for x in row)
                    for row in self.coord.to_numpy()
                ))

    def tolmp(self, outfile=None, atom_style='atomic'):
        """Write LAMMPS data file.

        Args:
            outfile: output filename (default: infile base + .data)
            atom_style: 'atomic' (default), 'charge', or 'full'
        """
        if outfile is None:
            if self._filename:
                outfile = self._filename.rsplit('.', 1)[0] + '.data'
            else:
                outfile = 'structure.data'

        ele_types = list(self.coord.index.unique())
        ele_to_type = {e: i + 1 for i, e in enumerate(ele_types)}
        n_atoms = len(self.coord)
        n_types = len(ele_types)
        lattice = self.lattice

        # Box bounds from lattice vectors
        xlo, xhi = 0.0, lattice[0][0]
        ylo, yhi = 0.0, lattice[1][1]
        zlo, zhi = 0.0, lattice[2][2]
        xy = lattice[1][0]
        xz = lattice[2][0]
        yz = lattice[2][1]

        with open(outfile, 'w') as f:
            f.write('Generated by toolkit\n\n')
            f.write(f'{n_atoms} atoms\n')
            f.write(f'{n_types} atom types\n')

            # Box
            if abs(xy) > 1e-6 or abs(xz) > 1e-6 or abs(yz) > 1e-6:
                f.write(f'{xlo:16.10f} {xhi:16.10f} xlo xhi\n')
                f.write(f'{ylo:16.10f} {yhi:16.10f} ylo yhi\n')
                f.write(f'{zlo:16.10f} {zhi:16.10f} zlo zhi\n')
                f.write(f'{xy:16.10f} {xz:16.10f} {yz:16.10f} xy xz yz\n')
            else:
                f.write(f'{xlo:16.10f} {xhi:16.10f} xlo xhi\n')
                f.write(f'{ylo:16.10f} {yhi:16.10f} ylo yhi\n')
                f.write(f'{zlo:16.10f} {zhi:16.10f} zlo zhi\n')

            f.write('\n')

            # Masses
            f.write('Masses\n\n')
            for elem, tid in ele_to_type.items():
                mass = next((m for m, e in _MASS_TO_ELEM.items() if e == elem), 1.0)
                f.write(f'{tid} {mass:.6f}\n')
            f.write('\n')

            # Atoms
            atom_type_str = 'atomic' if atom_style == 'atomic' else atom_style
            f.write(f'Atoms # {atom_type_str}\n\n')
            atom_id = 0
            for elem, row in self.coord.iterrows():
                atom_id += 1
                tid = ele_to_type[elem]
                x, y, z = row['x'], row['y'], row['z']
                if atom_style == 'atomic':
                    f.write(f'{atom_id} {tid} {x:16.10f} {y:16.10f} {z:16.10f}\n')
                elif atom_style == 'charge':
                    f.write(f'{atom_id} {tid} 0.0 {x:16.10f} {y:16.10f} {z:16.10f}\n')
                elif atom_style == 'full':
                    f.write(f'{atom_id} 1 {tid} 0.0 {x:16.10f} {y:16.10f} {z:16.10f}\n')
        return outfile

    def toxyz(self, outfile=None):
        """Write XYZ file."""
        if outfile is None:
            if self._filename and '.' in self._filename:
                outfile = self._filename.rsplit('.', 1)[0] + '.xyz'
            else:
                outfile = 'structure.xyz'

        with open(outfile, 'w') as f:
            f.write(f'{len(self.coord)}\nGenerated by toolkit\n')
            for row in self.coord.reset_index().to_numpy():
                line = '\t'.join(
                    [str(row[0])] + [f'{float(x):0.6f}' for x in row[1:]]
                )
                f.write(line + '\n')
